import { DEFAULT_WEATHER_CONTEXT } from './config'

export const state = {
  uploadedPhoto: '',
  uploadedPhotoFile: null,
  uploadedPhotoFingerprint: '',
  syncedPhotoFingerprint: '',
  avatarDataUrl: '',
  figureId: '',
  figureStatus: 'idle',
  figureUploadStatus: 'idle',
  figureSourceUrl: '',
  figures: [],
  clothCatalog: [],
  clothLookup: {},
  clothDetail: null,
  clothIndexStatus: {},
  selectedClothIds: [],
  wardrobeMode: 'fallback',
  wardrobeStatus: '',
  lastRecommendation: null,
  historyEntries: [],
  historyMode: 'local',
  historyFilter: 'all',
  historyStatus: 'idle',
  historyScrollTween: null,
  historyScrollTrigger: null,
  historyDistortions: [],
  dashboardAggregate: {
    source: 'local',
    status: 'idle',
    error: '',
    histories: [],
    styles: [],
    tryons: [],
    tasks: [],
    lastSyncedAt: 0,
  },
  aiFxRaf: 0,
  aiFxCleanup: null,
  aiFxController: null,
  aiParallaxCleanup: null,
  authMode: 'login',
  authToken: '',
  authUser: null,
  authVerificationStatus: 'idle',
  dashboardOpen: false,
  weatherContext: {
    ...DEFAULT_WEATHER_CONTEXT,
  },
  selections: {
    top: 'graphite',
    bottom: 'stone',
    shoes: 'onyx',
    weather: 'cloudy',
    occasion: 'office',
  },
}
